export const invoiceThemes = [
  {
    name: "Classic Blue",
    src: "https://th.bing.com/th/id/OIP.00j06LqDnG9abzHdfUgScwHaJl?r=0&rs=1&pid=ImgDetMain",
    primaryColor: "#1E40AF",
    textColor: "#1F2937",
    accentColor: "#3B82F6",
    fontFamily: "Inter, sans-serif",
    borderColor: "#BFDBFE",
  },
  {
    name: "Emerald Green",
    src: "https://www.invoiceberry.com/img/homepage/free_invoice_templates/new/countries/US.png",
    primaryColor: "#047857",
    textColor: "#111827",
    accentColor: "#34D399",
    fontFamily: "Roboto, sans-serif",
    borderColor: "#A7F3D0",
  },
  {
    name: "Bold Crimson",
    src: "https://th.bing.com/th/id/OIP.-5IoT8pgTw6FUtRnGXDQVgHaHa?r=0&o=7rm=3&rs=1&pid=ImgDetMain",
    primaryColor: "#991B1B",
    textColor: "#1F2937",
    accentColor: "#F87171",
    fontFamily: "Open Sans, sans-serif",
    borderColor: "#FECACA",
  },
  {
    name: "Modern Indigo",
    src: "https://cdn.geckoandfly.com/wp-content/uploads/2019/06/sales-services-invoice-20.jpg",
    primaryColor: "#3730A3",
    textColor: "#1F2937",
    accentColor: "#6366F1",
    fontFamily: "Roboto, sans-serif",
    borderColor: "#C7D2FE",
  },
  {
    name: "Neutral Gray",
    src: "https://th.bing.com/th/id/OIP.Yz9j6gw0gkewJAWiyBnDIAHaJl?r=0&rs=1&pid=ImgDetMain",
    primaryColor: "#6B7280",
    textColor: "#111827",
    accentColor: "#9CA3AF",
    fontFamily: "Open Sans, sans-serif",
    borderColor: "#E5E7EB",
  },
  {
    name: "Vivid Coral",
    src: "https://images.template.net/943/Blank-Commercial-Invoice-Template.jpg",
    primaryColor: "#F43F5E",
    textColor: "#111827",
    accentColor: "#FB7185",
    fontFamily: "Poppins, sans-serif",
    borderColor: "#FFE4E6",
  },
  {
    name: "Golden Amber",
    src: "https://i.etsystatic.com/27168960/r/il/c11dd7/6156761403/il_1588xN.6156761403_i15u.jpg",
    primaryColor: "#E8BE14",
    textColor: "#1F2937",
    accentColor: "#FBBF24",
    fontFamily: "Inter, sans-serif",
    borderColor: "#FEF3C7",
  },
  {
    name: "Sleek Teal",
    src: "https://th.bing.com/th/id/OIP.EWd5HFNGj5MywXNqLsiNigHaJl?r=0&o=7rm=3&rs=1&pid=ImgDetMain",
    primaryColor: "#0F766E",
    textColor: "#111827",
    accentColor: "#2DD4BF",
    fontFamily: "Roboto, sans-serif",
    borderColor: "#A5F3FC",
  },
  {
    name: "Royal Purple",
    src: "https://th.bing.com/th/id/OIP.JoQvO9qIWPYJgK5ihS93qwAAAA?r=0&rs=1&pid=ImgDetMain",
    primaryColor: "#6D28D9",
    textColor: "#1F2937",
    accentColor: "#A78BFA",
    fontFamily: "Poppins, sans-serif",
    borderColor: "#EDE9FE",
  },
  {
    name: "Charcoal Minimal",
    src: "https://img.freepik.com/free-vector/minimal-invoice-template-design_480724-457.jpg?w=900",
    primaryColor: "#374151",
    textColor: "#111827",
    accentColor: "#6B7280",
    fontFamily: "Inter, sans-serif",
    borderColor: "#D1D5DB",
  },
  {
    name: "Ocean Breeze",
    src: "https://i.postimg.cc/q7TzFvVv/Screenshot-2025-07-09-003134.png",
    primaryColor: "#1E88E5",
    textColor: "#1F2937",
    accentColor: "#60A5FA",
    fontFamily: "Open Sans, sans-serif",
    borderColor: "#BBDEFB",
  },
  {
    name: "Forest Sage",
    src: "https://th.bing.com/th/id/OIP.J7zmzs2nhzT4GwtPqV_BPQHaHM?r=0&rs=1&pid=ImgDetMain",
    primaryColor: "#15803D",
    textColor: "#111827",
    accentColor: "#4ADE80",
    fontFamily: "Roboto, sans-serif",
    borderColor: "#BBF7D0",
  },
];